version: "0.1"
services:
  mariadb:
    container_name: "winston-mariadb"
    image: mariadb:11.3.2
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=$WINSTON_DB_ROOT_PASSWORD
      - WINSTON_DB=$WINSTON_DB
      - WINSTON_DB_USER=$WINSTON_DB_USER
      - WINSTON_DB_PASSWORD=$WINSTON_DB_PASSWORD
    volumes:
      - $HOME/mariadb/data:/data
      - ./mariadb:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      timeout: 20s
      retries: 10

  app:
    container_name: "winston-app"
    build: ./app
    environment:
      - WINSTON_DB=$WINSTON_DB
      - WINSTON_DB_USER=$WINSTON_DB_USER
      - WINSTON_DB_PASSWORD=$WINSTON_DB_PASSWORD
    depends_on:
      mariadb:
        condition: service_healthy

  swagger: 
    container_name: "winston-swagger"
    image: "swaggerapi/swagger-ui"
    environment:
      - BASE_URL=/swagger
      - SWAGGER_JSON_URL=${SWAGGER_PROTOCOL}://${PROXY_HOST}:${SWAGGER_PORT}/rest/openapi.json
    depends_on:
      - app

  nginx:
    container_name: "winston-nginx"
    build: ./nginx
    ports:
      - "8080:8080"
    depends_on:
      - app
      - swagger
    
