#!/bin/bash

mariadb -u root -p${MARIADB_ROOT_PASSWORD} -e "CREATE DATABASE ${WINSTONDB} /*\!40100 DEFAULT CHARACTER SET utf8 */;"
mariadb -u root -p${MARIADB_ROOT_PASSWORD} -e "CREATE USER ${WINSTONDBUSER}@localhost IDENTIFIED BY '${WINSTONDBPASSWORD}';"
mariadb -u root -p${MARIADB_ROOT_PASSWORD} -e "GRANT ALL PRIVILEGES ON ${WINSTONDB}.* TO '${WINSTONDBUSER}'@'localhost';"
mariadb -u root -p${MARIADB_ROOT_PASSWORD} -e "FLUSH PRIVILEGES;"
